### ISSUE TITLE
New resource

### ISSUE THREAD

**Issue by mostafa-asg** [willianpaixao/awesome-german#2]
[Bolbol](https://github.com/mostafa-asg/bolbol) is a terminal based application to practice and remembering new vocabulary. I developed it to learn German and it helped me a lot. There are many German sentences in the [Languages](https://github.com/mostafa-asg/bolbol/tree/master/languages) folder and almost every day it will be updated.
It would be nice of you, if you add this utility to [awesome-german](https://github.com/willianpaixao/awesome-german).

**Comment by willianpaixao** [comment]
That looks fun! I'll take a look.
Thanks for sharing.
